INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train, createdAt, updatedAt) VALUES ("MN140","Active", "Manager", "Tiffany", "S", "Lerold", "500 Lyle Ave","", "Minneapolis", "MN", "55412", "7635594380", "tl@gmail.com", "tl@tanner-companies.com", "2020-06-08", "1994-11-06", "F", "Salaried", "Biweekly", 1500.00, "Email", true, true, true, true, true, true, true, false, now(), now());
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN129", "Active", "Stylist", "Abigail", "", "Hamilton", "3050 Stevens Ave N", "#7", "Minneapolis", "MN", "55411", "7635594495", "ma@gmail.com", "ma@tanner-companies.com", "2020-03-01", "1992-02-18", "F", "Hourly", "Biweekly", 16.00, "Indeed", true, true, true, true, true, true, false, false);
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN140", "Active", "Stylist", "Lauren", "L", "Tourville", "510 S 35th Street", "",  "Roseville", "MN", "55113", "7635594610", "lt@gmail.com", "lt@tanner-companies.com", "2020-01-26", "1985-11-04", "F", "Hourly", "Biweekly", 16.00,"Behind the Chair", false, true, true, false, true, true, true, true);
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN129", "Active", "Stylist", "Pordea","", "Carpenter", "7835 Elmo Pike Ct", "", "Crystal", "MN", "55427", "7635594725", "pc@yahoo.com", "pc@tanner-companies.com", "2019-12-21", "1991-06-29", "F", "Hourly", "Biweekly", 16.00, "Email", true, false, true, false, false, true, false, false);
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN129", "Active", "Stylist", "Corrie", "M", "Bratcher", "7124 Industrial Ave N", "", "Minneapolis", "MN", "55440", "7635594840", "cb@gmail.com", "cb@tanner-companies.com", "2019-08-31", "1985-11-19", "F", "Hourly", "Biweekly", 16.00, "Text", true, true, true, true, false, true, true, false);
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN117", "Active", "Stylist", "Monae", "M", "Jones", "389 Portland Ave NE", "Apt 1", "New Hope", "MN", "55428", "7635594955", "mj@gmail.com", "mj@tanner-companies.com", "2019-08-04", "1991-09-15", "F", "Hourly", "Biweekly", 16.00, "Indeed", false, true, true, true, false, false, false, true);
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN129", "Active", "Stylist", "Feather", "M", "Hicks", "7601 84th Ave N", "#2", "Brooklyn Center", "MN","55429", "7635595070", "fh@gmail.com", "fh@tanner-companies.com", "2019-04-13", "1979-05-27", "F", "Hourly", "Biweekly", 16.00, "Referral", true, true, true, false, true, false, true, false);
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN140", "Active", "Asst Mgr", "Morgan", "L", "Wilson", "853 Wilbur Lane NW", "", "Minneapolis", "MN", "55432", "7635595185", "mw@gmail.com", "mw@tanner-companies.com", "2018-10-27", "1973-04-02", "F", "Hourly", "Biweekly", 16.00, "Text", true, false, true, true, true, false, false, false); 
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN117", "Active", "Stylist", "Kimberly", "M", "Boyd", "300 Bannister St", "#104", "Minneapolis", "MN", "55428", "7635595300", "kb@gmail.com", "kb@tanner-companies.com", "2018-06-10", "1962-12-03", "F", "Hourly", "Biweekly", 16.00, "Indeed", false, true, true, true, true, true, true, true); 
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN129", "Active", "Manager", "Kayla", "L", "Volk", "14108 60th Ave N", "", "Coon Rapids", "MN", "55448", "7635595415", "kv@gmail.com", "kv@tanner-companies.com", "2018-03-26", "1971-07-18", "F", "Salaried", "Biweekly", 1400.00, "Indeed", true, true, true, true, false, true, false, false);
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("Tannerco", "Active", "Area Mgr", "Rhianna", "", "Flores", "8400 Hampton Blvd", "#246", "St Paul", "MN", "55101", "7635595530", "rf@gmail.com", "rf@tanner-companies.com", "2018-03-18", "1983-11-27", "F", "Salaried", "Biweekly", 1400.00, "Craiglist", true, true, true, false, false, true, true, false);
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN129", "Active", "Stylist", "Lorina", "Y", "Maya", "4907 Butcher Ave N", "", "Plymouth", "MN", "55442", "7635595645", "lm@hotmail.com", "lm@tanner-companies.com", "2018-01-01", "1981-04-11", "F", "Hourly", "Biweekly", 16.00, "Indeed", false, false, true, false, false, true, false, true); 
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN129", "Active", "Stylist", "Maria", "", "Rodriguez", "3229 Elsies Ave", "", "New Hope", "MN", "55428", "7635595760", "mr@yahoo.com", "mr@tanner-companies.com", "2017-08-07", "1992-12-09", "F", "Hourly", "Biweekly", 16.00, "Craiglist", true, true, true, true, true, true, true, true); 
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN117", "Active", "Sr Manager", "Cinthia", "R", "Kintner", "3031 Forrester Ave S", "Apt 135", "Brooklyn Center", "MN", "55429", "7635595875", "ck@yahoo.com", "ck@tanner-companies.com", "2017-05-28", "1996-06-13", "F", "Salaried", "Biweekly", 1400.00, "Referral", true, true, true, true, true, false, false, false); 
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN117", "Terminated", "Stylist", "Kang", "L", "Khang", "5005 Washburn Ave N", "", "Minneapolis", "MN", "55419", "7635595990", "kk@gmail.com", "kk@tanner-companies.com", "2020-03-01", "1977-03-20", "F", "Hourly", "Biweekly", 16.00, "Indeed", false, true, true, false, true, false, true, true); 
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN117", "Terminated", "Stylist", "Shanna", "R", "Daniels-Bridges", "1709 Main Street N", "", "Minneapolis", "MN", "55416", "7635596105", "sd@gmail.com", "sd1@tanner-companies.com", "2020-02-02", "1996-08-18", "F", "Hourly", "Biweekly", 16.00, "Text", true, true, true, false, false, false, false, false); 
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN117", "Terminated", "Stylist", "Daniel", "", "Steele", "2004 90th PL S", "", "Minneapolis", "MN", "55430", "7635596220", "sd@yahoo.com", "sd2@tanner-companies.com", "2019-12-11", "1990-05-19", "M", "Hourly", "Biweekly", 16.00, "Indeed", true, false, true, true, false, true, true, false); 
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN129", "Terminated", "Stylist", "Rosalind", "", "Blake", "4534 Deerpoint Ave S", "", "Minneapolis", "MN", "55411", "7635596335", "rb@gmail.com", "rb@tanner-companies.com", "2019-12-05", "1995-11-30", "F", "Hourly", "Biweekly", 16.00, "Email", false, true, true, true, false, true, false, true); 
INSERT INTO employees (department, status, role, first_name,  middle_init, last_name, address_line1, address_line2, city, state, zip, primary_phone, personal_email, work_email, hire_date, birth_date, gender, pay_type, pay_freq, pay_rate, app_source, app_rec, i9_rec, w4_rec, ca_rec, exp_rec, tmh_rec, welcome_train, core_camp_train) VALUES ("MN129", "Terminated", "Stylist", "Stephaniee", "", "Gibson", "2510 Cicero Ave S", "",  "Minneapolis", "MN", "55408", "7635596450", "sg@gmail.com", "sg@tanner-companies.com", "2019-12-05", "1991-06-17", "F", "Hourly", "Biweekly", 16.00, "Text", false, true, true, false, true, true, true, false);
insert into employees(first_name, last_name, employees.role, department, status, primary_phone, personal_email, hire_date, birth_date)
values ("john", "ferro", "admin", "IT","","","jonafi@gmail.com",0, 0);
insert into employees(first_name, last_name, employees.role, department, status, primary_phone, personal_email, hire_date, birth_date)
values ("tim", "tanner", "admin", "IT","","","timtanner@tanner-companies.com",0, 0);
insert into employees(first_name, last_name, employees.role, department, status, primary_phone, personal_email, hire_date, birth_date, createdAt, updatedAt)
values ("christian", "gonzalez", "admin", "IT","","","tiempoautomata@gmail.com",0, 0, now(), now());
insert into employees(first_name, last_name, employees.role, department, status, primary_phone, personal_email, hire_date, birth_date)
values ("william", "sorn", "admin", "IT","","","sornwilliam@gmail.com",0, 0);
insert into employees(first_name, last_name, employees.role, department, status, primary_phone, personal_email, hire_date, birth_date)
values ("vanida ", "somchaleunsouk", "admin", "IT","","","vsomsouk@gmail.com",0, 0);